### PR TITLE
ENGAGE-70 fixed toggle

### PR DESCRIPTION
**Pull request by jeisenman23**
This pull request fixes a collapsable menu where the arrow indicates to expand when collapse and collapse when expanded. Here are the new changes:
image
image
Here was the defective view:
image

### CODE REVIEW

**Comment by hannamocha** [comment]
This should still function as a collapsable menu so when the user clicks it, the menu collapses and the arrow points the other way.

**Comment by jeisenman23** [comment]
> This should still function as a collapsable menu so when the user clicks it, the menu collapses and the arrow points the other way. 

It does. See the first two pictures and try to test.

**Review by hannamocha — APPROVED** [review]
My local isn't working for the dropdowns for some reason with the dropdowns and I think that's breaking the other javascript, but these screenshots look good.

**Comment by jgu2** [comment]
Needs to resolve the conflicts for testing.

**Pull request merged**
